import { ToolContext, ToolResult, ok, err } from './context.js';
import { toErrorResponse } from '../errors.js';
import { FieldDefinition } from '../types/smartsuite.js';
import { proseMirrorToText } from '../utils/prosemirror.js';
import { buildAiPromptDoc } from '../utils/aiPrompt.js';

/**
 * Fold an `aiPrompt` template into `params.ai_agent.instructions` as a ProseMirror pill doc, preserving
 * any other ai_agent settings (model, enabled, etc.). `{{slug}}` tokens become field-reference pills;
 * returns { params, unknownSlugs } so callers can reject a prompt that references unknown fields.
 */
function applyAiPrompt(
  params: Record<string, unknown>,
  aiPrompt: string,
  fields: Array<{ slug: string; label: string; field_type: string }>,
): { params: Record<string, unknown>; unknownSlugs: string[] } {
  const { doc, unknownSlugs } = buildAiPromptDoc(aiPrompt, fields);
  const existingAgent = (params['ai_agent'] && typeof params['ai_agent'] === 'object' ? params['ai_agent'] : {}) as Record<string, unknown>;
  const ai_agent = { enabled: true, ...existingAgent, instructions: doc };
  return { params: { ...params, ai_agent }, unknownSlugs };
}

/**
 * Field help text is stored as a ProseMirror doc in `params.help_doc` (the legacy
 * `help_text` key is almost always null). Always emit both keys so absence is
 * unambiguous: helpText is null when there is none.
 */
export function helpTextOf(field: FieldDefinition): { helpText: string | null; helpTextFormat: string | null } {
  const fromDoc = proseMirrorToText(field.params.help_doc);
  const legacy = field.params.help_text ?? '';
  const text = (fromDoc || legacy).trim();
  return {
    helpText: text || null,
    helpTextFormat: field.params.help_text_display_format ?? null,
  };
}

/** Per-field-type extras relevant to schema scoring (record-title, autonumber, linked, AI). */
function typeSpecific(field: FieldDefinition): Record<string, unknown> {
  const p = field.params;
  const out: Record<string, unknown> = {};

  if (field.field_type === 'recordtitlefield') {
    out['isAutoGenerated'] = p.is_auto_generated ?? false;
    if (p.template) out['template'] = p.template;
  }

  if (field.field_type === 'autonumberfield') {
    out['autoNumber'] = {
      prefix: p.prefix ?? '',
      suffix: p.suffix ?? '',
      startingNumber: p.starting_number ?? null,
      leadingZeros: p.leading_zeros ?? 0,
      includeLabels: p.include_labels ?? false,
    };
  }

  if (field.field_type === 'linkedrecordfield') {
    if (p.display_format) out['displayFormat'] = p.display_format;
    if (p.entries_allowed) out['entriesAllowed'] = p.entries_allowed;
    if (p.visible_fields?.length) out['visibleFields'] = p.visible_fields;
  }

  if (p.ai_agent) {
    out['aiField'] = {
      enabled: p.ai_agent.enabled ?? false,
      model: p.ai_agent.model ?? null,
      instructions: p.ai_agent.instructions ?? null,
      enableInternetSearch: p.ai_agent.enable_internet_search ?? false,
      runAutomatically: p.ai_agent.run_automatically ?? false,
    };
  }

  return out;
}

export async function handleListFields(
  args: Record<string, unknown>,
  ctx: ToolContext,
): Promise<ToolResult> {
  const applicationId = args['applicationId'] as string;
  try {
    const schema = await ctx.client.getApplicationSchema(applicationId);
    // Token-lean column list: slug/label/type + enum values + link targets, omitting false flags
    // and help text (use smartsuite_describe_field for those). Cheapest way to learn a table's fields.
    const fields = (schema.structure ?? []).map((f) => {
      const item: Record<string, unknown> = { slug: f.slug, label: f.label, type: f.field_type };
      if (f.params.required) item['required'] = true;
      if (f.params.primary) item['primary'] = true;
      if (f.params.choices?.length) item['options'] = f.params.choices.map((c) => ({ value: c.value, label: c.label }));
      if (f.params.linked_application) item['linkedApplication'] = f.params.linked_application;
      return item;
    });
    return ok({ items: fields, count: fields.length });
  } catch (e) {
    const er = toErrorResponse(e);
    return { content: [{ type: 'text', text: JSON.stringify({ error: er }, null, 2) }], isError: true };
  }
}

export async function handleDescribeField(
  args: Record<string, unknown>,
  ctx: ToolContext,
): Promise<ToolResult> {
  const applicationId = args['applicationId'] as string;
  const fieldSlug = args['fieldSlug'] as string;
  try {
    const schema = await ctx.client.getApplicationSchema(applicationId);
    const field = (schema.structure ?? []).find((f) => f.slug === fieldSlug);
    if (!field) {
      return {
        content: [{ type: 'text', text: JSON.stringify({ error: { code: 'SMARTSUITE_NOT_FOUND', message: `Field "${fieldSlug}" not found in application ${applicationId}` } }, null, 2) }],
        isError: true,
      };
    }
    return ok({
      slug: field.slug,
      label: field.label,
      type: field.field_type,
      required: field.params.required ?? false,
      primary: field.params.primary ?? false,
      hidden: field.params.hidden ?? false,
      ...helpTextOf(field),
      ...(field.params.choices?.length
        ? { options: field.params.choices.map((c) => ({ value: c.value, label: c.label, color: c.value_color })) }
        : {}),
      ...(field.params.linked_application ? { linkedApplication: field.params.linked_application } : {}),
      ...(field.params.linked_field_slug ? { linkedFieldSlug: field.params.linked_field_slug } : {}),
      ...(field.params.max_length ? { maxLength: field.params.max_length } : {}),
      ...(field.params.new_choices_allowed !== undefined ? { newChoicesAllowed: field.params.new_choices_allowed } : {}),
      ...(field.params.formula
        ? {
            formula: field.params.formula,
            ...(field.params.is_advanced !== undefined ? { isAdvanced: field.params.is_advanced } : {}),
            ...(field.params.target_field_structure?.field_type
              ? { returnType: field.params.target_field_structure.field_type }
              : {}),
          }
        : {}),
      ...typeSpecific(field),
    });
  } catch (e) {
    const er = toErrorResponse(e);
    return { content: [{ type: 'text', text: JSON.stringify({ error: er }, null, 2) }], isError: true };
  }
}

import { markdownToProseMirror } from '../utils/prosemirror.js';

function schemaWriteGuard(ctx: ToolContext): ToolResult | null {
  if (ctx.config.mode === 'readonly') {
    return err('MCP_MODE_BLOCKED', 'Schema writes are blocked in readonly mode. Set SMARTSUITE_MCP_MODE=readwrite or admin.');
  }
  if (!ctx.config.enableSchemaWrite) {
    return err('MCP_MODE_BLOCKED', 'Schema writes are disabled. Set SMARTSUITE_ENABLE_SCHEMA_WRITE=true to edit field help text.');
  }
  return null;
}

/**
 * Set (or clear) a field's help text. Read-modify-write: fetch the full field definition, set
 * params.help_doc (markdown → ProseMirror) + help_text_display_format, and PUT it via change_field.
 * change_field applies asynchronously, so we report the submitted value rather than reading back.
 */
export async function handleSetFieldHelpText(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const helpText = args['helpText'] as string | undefined;
  const displayFormat = args['displayFormat'] as string | undefined;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');
  if (helpText === undefined && displayFormat === undefined) {
    return err('SMARTSUITE_VALIDATION_ERROR', 'Provide helpText (markdown; "" clears it) and/or displayFormat.');
  }

  try {
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);

    // Read-modify-write the raw field object so all params (choices, nested, etc.) are preserved.
    const next = JSON.parse(JSON.stringify(field)) as FieldDefinition & { params: Record<string, unknown> };
    const helpDoc = helpText !== undefined ? markdownToProseMirror(helpText) : (field.params.help_doc ?? null);
    next.params.help_doc = helpDoc;
    if (displayFormat !== undefined) next.params.help_text_display_format = displayFormat;
    else if (helpDoc && !next.params.help_text_display_format) next.params.help_text_display_format = 'tooltip';

    const preview = { slug, label: field.label, helpText: helpText !== undefined ? (helpText || null) : helpTextOf(field).helpText, displayFormat: next.params.help_text_display_format ?? null };
    if (!confirm) return ok({ dryRun: true, would: preview, note: 'Re-call with confirm:true to apply.' });

    await ctx.client.changeField(applicationId, next as FieldDefinition);
    return ok({ updated: true, ...preview, note: 'Submitted. change_field applies asynchronously; re-read the field in a moment to see it reflected.' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

import { generateFieldSlug } from './formulas.js';

/** Build a field definition envelope (params pass through to SmartSuite, which fills defaults). */
export function buildFieldDef(slug: string, label: string, fieldType: string, params: Record<string, unknown> = {}): FieldDefinition {
  return { slug, label, field_type: fieldType, params: params as FieldDefinition['params'] };
}

const SELECT_FIELD_TYPES = new Set(['singleselectfield', 'multipleselectfield', 'statusfield']);
/** Single/multi select choices carry a description (`value_help_text`) and numeric value (`weight`); status choices do not. */
const WEIGHTED_SELECT_TYPES = new Set(['singleselectfield', 'multipleselectfield']);
/** SmartSuite's default choice-color palette (the sequence new choices cycle through). */
const CHOICE_PALETTE = [
  '#0C41F3', '#00B3FA', '#199A27', '#F1273F', '#FF702E', '#FDA80D', '#673DB6', '#CD286A', '#00B2A8', '#2D2D2D',
  '#3A86FF', '#4ECCFD', '#3EAC40', '#FF5757', '#FF9210', '#FFB938', '#883CD0', '#EC506E', '#17C4C4', '#6A849B',
];

/**
 * For select-type fields, normalize every choice to the shape SmartSuite's UI produces, so MCP-created
 * choices render and behave identically:
 *  - `value_color` / `value_order` (all select types): a choice with no color renders incorrectly until
 *    you open field settings and pick one, so we assign colors from the default palette (by position).
 *  - `value_help_text` (single/multi only): the choice *description* shown in the dropdown; defaults to ''.
 *  - `weight` (single/multi only): the choice's *numeric value* (used by formulas/rollups); defaults to 1,
 *    matching the UI. Callers set it per choice to give options distinct numeric values.
 * Any explicitly-provided value is preserved.
 */
/**
 * camelCase spellings accepted as aliases for the snake_case params SmartSuite actually stores.
 *
 * This exists because the READ and WRITE sides of the MCP disagree: describe_application/list_fields
 * emit `linkedApplication` (camelCase), while add_field/change_field require `linked_application`.
 * Round-tripping a field you just read therefore produced a linked-record field with a NULL target —
 * SmartSuite ignores the unknown key, creates the field, and reports success. Accepting both
 * spellings closes that trap instead of leaving it to the caller to notice.
 */
const PARAM_ALIASES: Record<string, string> = {
  linkedApplication: 'linked_application',
  entriesAllowed: 'entries_allowed',
  linkedField: 'linked_field',
  fieldSelection: 'field_selection',
  linkedFieldSlug: 'linked_field_slug',
  maxLength: 'max_length',
  displayFormat: 'display_format',
  valueHelpText: 'value_help_text',
};

/** SmartSuite derives a choice `value` from its label this way: "Ready for Review" -> "ready_for_review". */
export function choiceValueFromLabel(label: string): string {
  return String(label).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'option';
}

/** Rewrite camelCase param keys to the snake_case SmartSuite expects, at the top level and per choice. */
function applyParamAliases(params: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(params)) out[PARAM_ALIASES[k] ?? k] = v;
  if (Array.isArray(out['choices'])) {
    out['choices'] = (out['choices'] as unknown[]).map((c) =>
      c && typeof c === 'object' && !Array.isArray(c)
        ? Object.fromEntries(Object.entries(c as Record<string, unknown>).map(([k, v]) => [PARAM_ALIASES[k] ?? k, v]))
        : c,
    );
  }
  return out;
}

/**
 * Fill in the choice `value` SmartSuite requires but the tool never documented.
 *
 * A choice sent as `{label:"High"}` is not an error: SmartSuite accepts the field and stores
 * `choices: []`, so a select field arrives with no options and the call still reports success.
 * Values are derived from labels the way the UI does, and de-duplicated so two labels that
 * normalize alike ("In Progress" / "in-progress") do not collide into one option.
 */
function fillChoiceValues(fieldType: string, params: Record<string, unknown>): Record<string, unknown> {
  if (!SELECT_FIELD_TYPES.has(fieldType) || !Array.isArray(params['choices'])) return params;
  const seen = new Set<string>();
  const choices = (params['choices'] as Array<Record<string, unknown>>).map((c) => {
    if (!c || typeof c !== 'object') return c;
    const existing = c['value'];
    if (typeof existing === 'string' && existing.trim()) { seen.add(existing); return c; }
    let v = choiceValueFromLabel(String(c['label'] ?? ''));
    if (seen.has(v)) { let n = 2; while (seen.has(`${v}_${n}`)) n++; v = `${v}_${n}`; }
    seen.add(v);
    return { ...c, value: v };
  });
  return { ...params, choices };
}

/**
 * Params that, if missing, guarantee a broken field. SmartSuite creates the field anyway and
 * reports success, so these are caught here rather than discovered as an error badge later.
 */
function requiredParamError(fieldType: string, params: Record<string, unknown>): string | null {
  if (fieldType === 'linkedrecordfield') {
    const target = params['linked_application'];
    if (typeof target !== 'string' || !target.trim()) {
      return 'linkedrecordfield requires params.linked_application (the id of the table it links TO). '
        + 'Without it SmartSuite creates the field with a null target and it shows an error badge in the UI. '
        + '(camelCase linkedApplication — as returned by describe_application — is accepted and converted.)';
    }
  }
  if (fieldType === 'lookupfield' || fieldType === 'rollupfield') {
    for (const key of ['linked_field', 'field_selection']) {
      if (params[key] === undefined) {
        return `${fieldType} requires params.${key}. Without it the field is created but resolves to nothing.`;
      }
    }
  }
  return null;
}

/**
 * Normalize and validate a field's params before any write: camelCase aliases are converted,
 * select choices get the `value` SmartSuite silently requires, and params whose absence would
 * guarantee a broken field are rejected. Returns the params to send, or an error message.
 */
export function prepareFieldParams(
  fieldType: string,
  rawParams: Record<string, unknown>,
): { params: Record<string, unknown> } | { error: string } {
  const aliased = applyParamAliases(rawParams);
  const withValues = fillChoiceValues(fieldType, aliased);
  const rollupError = validateRollupParams(fieldType, withValues);
  if (rollupError) return { error: rollupError };
  const missing = requiredParamError(fieldType, withValues);
  if (missing) return { error: missing };
  return { params: normalizeChoices(fieldType, withValues) };
}

/**
 * Rollup aggregate functions that actually compute a value.
 *
 * SmartSuite's API does NOT validate this token: any string is accepted with HTTP 200, stored
 * verbatim, and the field reports `valid: true` with a computed target_field_structure — it just
 * returns null on every record. (`valid` tracks the target FIELD, not the function: a nonsense
 * function over a numeric target reads back valid, while `sum` over a non-numeric one does not.)
 * A wrong token is therefore invisible until someone opens a record, so we reject it here.
 *
 * Verified by controlled experiment (two linked records with values 10 and 4, one numeric target,
 * only the function string varied): sum→14, min→4, max→10, average→7.00, range→6 all computed;
 * count, concatenate, median, count_distinct, stdev, earliest, latest, percent_filled, first,
 * last and a deliberately bogus token all returned null.
 */
export const ROLLUP_FUNCTIONS = ['sum', 'min', 'max', 'average', 'range'] as const;

/** Tokens seen in the wild or previously advertised that do not compute — worth a pointed message. */
const ROLLUP_NON_FUNCTIONS: Record<string, string> = {
  count: 'Rollups have no "count" aggregate — use a countfield to count linked records, or sum a numeric field.',
  concatenate: 'A "concatenate" rollup returns nothing over a numeric target. To join values across a link, use a formula field with ARRAYJOIN([link].[field], "; ").',
  count_distinct: 'Not a rollup aggregate. COUNT_DISTINCT exists in formula fields.',
  median: 'Not a rollup aggregate. MEDIAN exists in formula fields.',
  stdev: 'Not a rollup aggregate. STDEV exists in formula fields.',
  earliest: 'Not a rollup aggregate. Use min over a date field, or RELATED_RECORD_SORT in a formula.',
  latest: 'Not a rollup aggregate. Use max over a date field, or RELATED_RECORD_SORT in a formula.',
};

/**
 * Reject a rollup whose `function` would silently compute nothing. Returns an error message,
 * or null when the params are fine (or the field is not a rollup).
 */
export function validateRollupParams(fieldType: string, params: Record<string, unknown>): string | null {
  if (fieldType !== 'rollupfield') return null;
  const fn = params['function'];
  if (fn === undefined) return null; // sparse params are allowed; SmartSuite fills its own default
  if (typeof fn !== 'string' || !ROLLUP_FUNCTIONS.includes(fn as (typeof ROLLUP_FUNCTIONS)[number])) {
    const hint = typeof fn === 'string' ? ROLLUP_NON_FUNCTIONS[fn.toLowerCase()] : undefined;
    return `Rollup function ${JSON.stringify(fn)} does not compute a value. Supported: ${ROLLUP_FUNCTIONS.join(', ')}.`
      + (hint ? ` ${hint}` : '')
      + ' SmartSuite accepts any token here without error and the field then returns null on every record, so this is blocked before the write.';
  }
  return null;
}

export function normalizeChoices(fieldType: string, params: Record<string, unknown>): Record<string, unknown> {
  if (!SELECT_FIELD_TYPES.has(fieldType) || !Array.isArray(params?.['choices'])) return params;
  const weighted = WEIGHTED_SELECT_TYPES.has(fieldType);
  const choices = (params['choices'] as Array<Record<string, unknown>>).map((c, i) => ({
    ...c,
    value_color: c['value_color'] ?? CHOICE_PALETTE[i % CHOICE_PALETTE.length],
    value_order: c['value_order'] ?? i,
    ...(weighted
      ? { value_help_text: c['value_help_text'] ?? '', weight: c['weight'] ?? 1 }
      : {}),
  }));
  return { ...params, choices };
}

/** Alias/choice-value pass with no required-param check — for a sparse patch merged onto an existing field. */
function applyPatchAliasesOnly(params: Record<string, unknown>): Record<string, unknown> {
  return applyParamAliases(params);
}

/** Shallow-merge a params patch onto existing params (patch keys win; others preserved). */
export function mergeFieldParams(existing: Record<string, unknown>, patch: Record<string, unknown>): Record<string, unknown> {
  return { ...existing, ...patch };
}

/**
 * Cap on fields per bulk call. Each `add_field` is its own ~1s round-trip (there is no bulk endpoint), so a
 * big batch is slow and more exposed to rate limiting; keeping batches bounded also keeps the dry-run
 * preview reviewable.
 */
export const MAX_BULK_FIELDS = 50;

export interface FieldSpec {
  slug: string;
  label: string;
  fieldType: string;
  params: Record<string, unknown>;
  aiPrompt?: string;
}

/**
 * Validate a caller-supplied `fields[]` array into specs with generated slugs. Every entry is checked
 * before anything is written, so a malformed entry can't leave a half-created batch behind. Returns an
 * error *message* rather than a ToolResult so both create_fields and create_application can frame it.
 */
export function parseFieldSpecs(raw: unknown, max = MAX_BULK_FIELDS): { specs: FieldSpec[] } | { error: string } {
  if (!Array.isArray(raw) || raw.length === 0) {
    return { error: 'fields must be a non-empty array of { fieldType, label, params? } objects.' };
  }
  if (raw.length > max) {
    return { error: `fields has ${raw.length} entries; the maximum per call is ${max}. Split it into smaller batches.` };
  }
  const specs: FieldSpec[] = [];
  for (let i = 0; i < raw.length; i++) {
    const entry = raw[i];
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) {
      return { error: `fields[${i}] must be an object with fieldType and label.` };
    }
    const rec = entry as Record<string, unknown>;
    const fieldType = rec['fieldType'];
    const label = rec['label'];
    if (typeof fieldType !== 'string' || !fieldType.trim()) {
      return { error: `fields[${i}].fieldType is required (e.g. textfield, numberfield, singleselectfield).` };
    }
    if (typeof label !== 'string' || !label.trim()) {
      return { error: `fields[${i}].label is required.` };
    }
    const rawParams = rec['params'];
    const params = rawParams && typeof rawParams === 'object' && !Array.isArray(rawParams)
      ? { ...(rawParams as Record<string, unknown>) }
      : {};
    const prepared = prepareFieldParams(fieldType, params);
    if ('error' in prepared) return { error: `fields[${i}] (${label}): ${prepared.error}` };
    const aiPrompt = typeof rec['aiPrompt'] === 'string' && rec['aiPrompt'].trim() ? rec['aiPrompt'] : undefined;
    specs.push({ slug: generateFieldSlug(), label, fieldType, params: prepared.params, aiPrompt });
  }
  return { specs };
}

/** Turn a spec into the field definition sent to SmartSuite (choice normalization included). */
export function fieldDefOf(spec: FieldSpec): FieldDefinition {
  // parseFieldSpecs already prepared these params; normalizeChoices is idempotent, so callers
  // that build a spec by hand still get correctly-shaped choices.
  return buildFieldDef(spec.slug, spec.label, spec.fieldType, normalizeChoices(spec.fieldType, spec.params));
}

/**
 * Resolve `aiPrompt` templates on a batch of specs against the application schema, fetching the schema at
 * most once for the whole batch. Returns an error message if any prompt references an unknown slug.
 *
 * A prompt can only reference fields that already exist — slugs for fields created in the same batch are
 * generated here, so a caller has no way to name them.
 */
async function applyBatchAiPrompts(
  specs: FieldSpec[],
  applicationId: string,
  ctx: ToolContext,
): Promise<string | null> {
  if (!specs.some((s) => s.aiPrompt)) return null;
  const schema = await ctx.client.getApplicationSchema(applicationId);
  for (const spec of specs) {
    if (!spec.aiPrompt) continue;
    const applied = applyAiPrompt(spec.params, spec.aiPrompt, schema.structure ?? []);
    if (applied.unknownSlugs.length) {
      return `aiPrompt for "${spec.label}" references unknown field slug(s): ${applied.unknownSlugs.join(', ')}. Use {{slug}} with slugs from smartsuite_list_fields.`;
    }
    spec.params = applied.params;
  }
  return null;
}

/**
 * Create many fields in one tool call.
 *
 * SmartSuite has no bulk add-field endpoint: `add_field` takes exactly one field, and `structure` is not
 * mutable on an existing table (any PATCH/PUT carrying a `structure` key — even an empty array — is a 500).
 * So this loops sequentially, N fields = N round-trips at roughly 1s each. The loop is deliberately serial:
 * parallel adds get rate-limited (429) rather than corrupting the schema, so concurrency loses fields
 * instead of saving time; a serial loop plus the client's 429 backoff is what actually lands all N.
 *
 * A failure does not abort the batch — every field is attempted and reported individually, so a partial
 * result is diagnosable and the caller can retry just the failures. To create a table *and* its fields,
 * prefer smartsuite_create_application with `fields`: that provisions them all in a single call.
 */
export async function handleCreateFields(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');

  const parsed = parseFieldSpecs(args['fields']);
  if ('error' in parsed) return err('SMARTSUITE_VALIDATION_ERROR', parsed.error);
  const { specs } = parsed;

  try {
    const promptError = await applyBatchAiPrompts(specs, applicationId, ctx);
    if (promptError) return err('SMARTSUITE_VALIDATION_ERROR', promptError);

    if (!confirm) {
      return ok({
        dryRun: true,
        applicationId,
        count: specs.length,
        would: specs.map((s) => ({ slug: s.slug, label: s.label, fieldType: s.fieldType, paramKeys: Object.keys(s.params).sort() })),
        note: `Creates ${specs.length} field(s) via ${specs.length} sequential API calls (~1s each, so roughly ${specs.length}s). Fields append to the end of the table in this order; use smartsuite_move_layout_field to reposition. SmartSuite fills type defaults for omitted params. Re-call with confirm:true to create.`,
      });
    }

    const results: Array<Record<string, unknown>> = [];
    for (const spec of specs) {
      try {
        await ctx.client.addField(applicationId, fieldDefOf(spec));
        results.push({ slug: spec.slug, label: spec.label, fieldType: spec.fieldType });
      } catch (e) {
        results.push({ slug: spec.slug, label: spec.label, fieldType: spec.fieldType, error: toErrorResponse(e).message });
      }
    }

    // One schema read for the whole batch (a per-field re-read would be N extra full-schema fetches), and
    // it is the authority on what landed — add_field returns an empty body.
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const bySlug = new Map((app.structure ?? []).map((f) => [f.slug, f]));
    for (const r of results) {
      const found = bySlug.get(r['slug'] as string) as (FieldDefinition & Record<string, unknown>) | undefined;
      r['created'] = found != null;
      if (found) r['field'] = fieldSummary(found);
    }

    const created = results.filter((r) => r['created'] === true).length;
    const failed = specs.length - created;
    return ok({
      created,
      failed,
      total: specs.length,
      ...(failed > 0
        ? { partial: true, hint: 'Some fields were not created. The created ones are already in place — re-call with only the failed entries.' }
        : {}),
      fields: results,
    });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

function fieldSummary(f: (FieldDefinition & Record<string, unknown>) | undefined): Record<string, unknown> | null {
  if (!f) return null;
  return { slug: f.slug, label: f.label, fieldType: f.field_type, paramKeys: Object.keys(f.params ?? {}).sort() };
}

/**
 * Create a field of any type. The caller supplies field_type + (optional, sparse) params; SmartSuite
 * fills type defaults. The tool generates the slug, places the field in the record-view layout, and
 * re-reads to report the result (add_field returns an empty body). New fields always append (the API
 * ignores any position anchor — see `addField`); use smartsuite_move_layout_field to place one elsewhere.
 * Schema-write gated; dry-run unless confirm. For several fields at once, use smartsuite_create_fields.
 */
export async function handleCreateField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const fieldType = args['fieldType'] as string;
  const label = args['label'] as string;
  let params = (args['params'] && typeof args['params'] === 'object' && !Array.isArray(args['params'])) ? (args['params'] as Record<string, unknown>) : {};
  const aiPrompt = args['aiPrompt'] as string | undefined;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!fieldType?.trim()) return err('SMARTSUITE_VALIDATION_ERROR', 'fieldType is required (e.g. textfield, numberfield, singleselectfield, linkedrecordfield).');
  if (!label?.trim()) return err('SMARTSUITE_VALIDATION_ERROR', 'label is required.');
  const prepared = prepareFieldParams(fieldType, params);
  if ('error' in prepared) return err('SMARTSUITE_VALIDATION_ERROR', prepared.error);
  params = prepared.params;

  try {
    // Build the AI prompt (ai_agent.instructions) from a {{slug}} template, resolving field references
    // against the schema so a dynamic prompt is a deterministic operation rather than hand-built pills.
    if (typeof aiPrompt === 'string' && aiPrompt.trim()) {
      const schema = await ctx.client.getApplicationSchema(applicationId);
      const applied = applyAiPrompt(params, aiPrompt, schema.structure ?? []);
      if (applied.unknownSlugs.length) return err('SMARTSUITE_VALIDATION_ERROR', `aiPrompt references unknown field slug(s): ${applied.unknownSlugs.join(', ')}. Use {{slug}} with slugs from smartsuite_list_fields.`);
      params = applied.params;
    }

    const slug = generateFieldSlug();
    const field = buildFieldDef(slug, label, fieldType, params);
    if (!confirm) {
      return ok({ dryRun: true, would: { slug, fieldType, label, paramKeys: Object.keys(params).sort(), position: '(appended to the end)' }, note: 'SmartSuite fills type defaults for omitted params. Re-call with confirm:true to create.' });
    }
    await ctx.client.addField(applicationId, field);
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const created = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    return ok({ created: true, slug, field: fieldSummary(created) });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/**
 * Update a field: change its label and/or merge a params patch (read-modify-write the full field
 * definition, then PUT via change_field). Applies asynchronously. Schema-write gated; dry-run unless confirm.
 */
export async function handleUpdateField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const label = args['label'] as string | undefined;
  const params = (args['params'] && typeof args['params'] === 'object' && !Array.isArray(args['params'])) ? (args['params'] as Record<string, unknown>) : undefined;
  const aiPrompt = args['aiPrompt'] as string | undefined;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');
  if (label === undefined && params === undefined && aiPrompt === undefined) {
    return err('SMARTSUITE_VALIDATION_ERROR', 'Provide label, params (a patch of param keys), and/or aiPrompt to update.');
  }

  try {
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);

    const next = JSON.parse(JSON.stringify(field)) as Record<string, any>;
    if (typeof label === 'string') next['label'] = label;
    if (params) {
      // Prepare the PATCH first (aliases + choice values), then merge, then validate the result:
      // a sparse patch can introduce a bad value on its own, and required params may already be
      // satisfied by the existing field.
      const patch = prepareFieldParams(next['field_type'], params);
      if ('error' in patch && !/requires params\./.test(patch.error)) {
        return err('SMARTSUITE_VALIDATION_ERROR', patch.error);
      }
      const merged = mergeFieldParams(next['params'] ?? {}, 'params' in patch ? patch.params : applyPatchAliasesOnly(params));
      const validated = prepareFieldParams(next['field_type'], merged);
      if ('error' in validated) return err('SMARTSUITE_VALIDATION_ERROR', validated.error);
      next['params'] = validated.params;
    }
    // Rebuild the AI prompt from a template, preserving the field's existing ai_agent (model, enabled).
    if (typeof aiPrompt === 'string' && aiPrompt.trim()) {
      const applied = applyAiPrompt(next['params'] ?? {}, aiPrompt, app.structure ?? []);
      if (applied.unknownSlugs.length) return err('SMARTSUITE_VALIDATION_ERROR', `aiPrompt references unknown field slug(s): ${applied.unknownSlugs.join(', ')}.`);
      next['params'] = applied.params;
    }

    const preview = { slug, label: next['label'], fieldType: next['field_type'], changedParams: params ? Object.keys(params).sort() : [], aiPromptSet: typeof aiPrompt === 'string' && aiPrompt.trim().length > 0 };
    if (!confirm) return ok({ dryRun: true, would: preview, note: 'Re-call with confirm:true to apply.' });

    await ctx.client.changeField(applicationId, next as unknown as FieldDefinition);
    return ok({ updated: true, ...preview, note: 'Submitted. change_field applies asynchronously; re-read the field in a moment to confirm.' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/**
 * Delete a field by slug. Requires readwrite/admin + SMARTSUITE_ENABLE_SCHEMA_WRITE + SMARTSUITE_ENABLE_DELETE.
 * Dry-run preview unless confirm:true. Destructive — the field and its data are removed.
 */
export async function handleDeleteField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;
  if (!ctx.config.enableDelete) {
    return err('MCP_MODE_BLOCKED', 'Field delete is disabled. Set SMARTSUITE_ENABLE_DELETE=true to enable.');
  }

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');

  try {
    const app = await ctx.client.getApplicationSchema(applicationId);
    const field = (app.structure ?? []).find((f) => f.slug === slug);
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);
    if (field.params?.system) return err('SMARTSUITE_VALIDATION_ERROR', `Field "${slug}" (${field.label}) is a system field and cannot be deleted.`);

    const info = { slug, label: field.label, fieldType: field.field_type };
    if (!confirm) return ok({ dryRun: true, wouldDelete: info, note: 'Removes the field and its data. Recoverable via smartsuite_restore_field. Re-call with confirm:true to delete.' });
    await ctx.client.deleteField(applicationId, slug);
    return ok({ deleted: true, ...info, restoreHint: 'Recover with smartsuite_restore_field (applicationId + slug).' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/** List soft-deleted fields across a solution's trash (read-only). The API returns them solution-wide
 * without per-application attribution, so results are not app-filtered. */
export async function handleListDeletedFields(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const solutionId = args['solutionId'] as string;
  if (!solutionId) return err('SMARTSUITE_VALIDATION_ERROR', 'solutionId is required (deleted fields are listed per solution).');
  try {
    const res = await ctx.client.listDeletedFields(solutionId);
    const items = res.map((f) => ({ slug: f['slug'], label: f['label'], fieldType: f['field_type'] }));
    return ok({ items, count: items.length, note: 'Restore with smartsuite_restore_field (you must supply the applicationId the field belonged to).' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/** Restore a soft-deleted field back into its application. Gated schema-write + confirm. */
export async function handleRestoreField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required (the deleted field slug, from smartsuite_list_deleted_fields).');

  try {
    if (!confirm) return ok({ dryRun: true, wouldRestore: { applicationId, slug }, hint: 'Re-call with confirm:true to restore this field.' });
    await ctx.client.restoreField(applicationId, slug);
    const app = await ctx.client.getApplicationSchema(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug);
    return ok({ restored: true, field: field ? { slug: field.slug, label: field.label, fieldType: field.field_type } : { slug } });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}
