import { ToolContext, ToolResult, ok } from './context.js';
import { toErrorResponse } from '../errors.js';
import { FieldDefinition } from '../types/smartsuite.js';
import { proseMirrorToText } from '../utils/prosemirror.js';

/**
 * Field help text is stored as a ProseMirror doc in `params.help_doc` (the legacy
 * `help_text` key is almost always null). Always emit both keys so absence is
 * unambiguous: helpText is null when there is none.
 */
export function helpTextOf(field: FieldDefinition): { helpText: string | null; helpTextFormat: string | null } {
  const fromDoc = proseMirrorToText(field.params.help_doc);
  const legacy = field.params.help_text ?? '';
  const text = (fromDoc || legacy).trim();
  return {
    helpText: text || null,
    helpTextFormat: field.params.help_text_display_format ?? null,
  };
}

/** Per-field-type extras relevant to schema scoring (record-title, autonumber, linked, AI). */
function typeSpecific(field: FieldDefinition): Record<string, unknown> {
  const p = field.params;
  const out: Record<string, unknown> = {};

  if (field.field_type === 'recordtitlefield') {
    out['isAutoGenerated'] = p.is_auto_generated ?? false;
    if (p.template) out['template'] = p.template;
  }

  if (field.field_type === 'autonumberfield') {
    out['autoNumber'] = {
      prefix: p.prefix ?? '',
      suffix: p.suffix ?? '',
      startingNumber: p.starting_number ?? null,
      leadingZeros: p.leading_zeros ?? 0,
      includeLabels: p.include_labels ?? false,
    };
  }

  if (field.field_type === 'linkedrecordfield') {
    if (p.display_format) out['displayFormat'] = p.display_format;
    if (p.entries_allowed) out['entriesAllowed'] = p.entries_allowed;
    if (p.visible_fields?.length) out['visibleFields'] = p.visible_fields;
  }

  if (p.ai_agent) {
    out['aiField'] = {
      enabled: p.ai_agent.enabled ?? false,
      model: p.ai_agent.model ?? null,
      instructions: p.ai_agent.instructions ?? null,
      enableInternetSearch: p.ai_agent.enable_internet_search ?? false,
      runAutomatically: p.ai_agent.run_automatically ?? false,
    };
  }

  return out;
}

export async function handleListFields(
  args: Record<string, unknown>,
  ctx: ToolContext,
): Promise<ToolResult> {
  const applicationId = args['applicationId'] as string;
  try {
    const schema = await ctx.client.getApplicationSchema(applicationId);
    // Token-lean column list: slug/label/type + enum values + link targets, omitting false flags
    // and help text (use smartsuite_describe_field for those). Cheapest way to learn a table's fields.
    const fields = (schema.structure ?? []).map((f) => {
      const item: Record<string, unknown> = { slug: f.slug, label: f.label, type: f.field_type };
      if (f.params.required) item['required'] = true;
      if (f.params.primary) item['primary'] = true;
      if (f.params.choices?.length) item['options'] = f.params.choices.map((c) => ({ value: c.value, label: c.label }));
      if (f.params.linked_application) item['linkedApplication'] = f.params.linked_application;
      return item;
    });
    return ok({ items: fields, count: fields.length });
  } catch (e) {
    const er = toErrorResponse(e);
    return { content: [{ type: 'text', text: JSON.stringify({ error: er }, null, 2) }], isError: true };
  }
}

export async function handleDescribeField(
  args: Record<string, unknown>,
  ctx: ToolContext,
): Promise<ToolResult> {
  const applicationId = args['applicationId'] as string;
  const fieldSlug = args['fieldSlug'] as string;
  try {
    const schema = await ctx.client.getApplicationSchema(applicationId);
    const field = (schema.structure ?? []).find((f) => f.slug === fieldSlug);
    if (!field) {
      return {
        content: [{ type: 'text', text: JSON.stringify({ error: { code: 'SMARTSUITE_NOT_FOUND', message: `Field "${fieldSlug}" not found in application ${applicationId}` } }, null, 2) }],
        isError: true,
      };
    }
    return ok({
      slug: field.slug,
      label: field.label,
      type: field.field_type,
      required: field.params.required ?? false,
      primary: field.params.primary ?? false,
      hidden: field.params.hidden ?? false,
      ...helpTextOf(field),
      ...(field.params.choices?.length
        ? { options: field.params.choices.map((c) => ({ value: c.value, label: c.label, color: c.value_color })) }
        : {}),
      ...(field.params.linked_application ? { linkedApplication: field.params.linked_application } : {}),
      ...(field.params.linked_field_slug ? { linkedFieldSlug: field.params.linked_field_slug } : {}),
      ...(field.params.max_length ? { maxLength: field.params.max_length } : {}),
      ...(field.params.new_choices_allowed !== undefined ? { newChoicesAllowed: field.params.new_choices_allowed } : {}),
      ...(field.params.formula
        ? {
            formula: field.params.formula,
            ...(field.params.is_advanced !== undefined ? { isAdvanced: field.params.is_advanced } : {}),
            ...(field.params.target_field_structure?.field_type
              ? { returnType: field.params.target_field_structure.field_type }
              : {}),
          }
        : {}),
      ...typeSpecific(field),
    });
  } catch (e) {
    const er = toErrorResponse(e);
    return { content: [{ type: 'text', text: JSON.stringify({ error: er }, null, 2) }], isError: true };
  }
}

import { err } from './context.js';
import { markdownToProseMirror } from '../utils/prosemirror.js';

function schemaWriteGuard(ctx: ToolContext): ToolResult | null {
  if (ctx.config.mode === 'readonly') {
    return err('MCP_MODE_BLOCKED', 'Schema writes are blocked in readonly mode. Set SMARTSUITE_MCP_MODE=readwrite or admin.');
  }
  if (!ctx.config.enableSchemaWrite) {
    return err('MCP_MODE_BLOCKED', 'Schema writes are disabled. Set SMARTSUITE_ENABLE_SCHEMA_WRITE=true to edit field help text.');
  }
  return null;
}

/**
 * Set (or clear) a field's help text. Read-modify-write: fetch the full field definition, set
 * params.help_doc (markdown → ProseMirror) + help_text_display_format, and PUT it via change_field.
 * change_field applies asynchronously, so we report the submitted value rather than reading back.
 */
export async function handleSetFieldHelpText(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const helpText = args['helpText'] as string | undefined;
  const displayFormat = args['displayFormat'] as string | undefined;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');
  if (helpText === undefined && displayFormat === undefined) {
    return err('SMARTSUITE_VALIDATION_ERROR', 'Provide helpText (markdown; "" clears it) and/or displayFormat.');
  }

  try {
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);

    // Read-modify-write the raw field object so all params (choices, nested, etc.) are preserved.
    const next = JSON.parse(JSON.stringify(field)) as FieldDefinition & { params: Record<string, unknown> };
    const helpDoc = helpText !== undefined ? markdownToProseMirror(helpText) : (field.params.help_doc ?? null);
    next.params.help_doc = helpDoc;
    if (displayFormat !== undefined) next.params.help_text_display_format = displayFormat;
    else if (helpDoc && !next.params.help_text_display_format) next.params.help_text_display_format = 'tooltip';

    const preview = { slug, label: field.label, helpText: helpText !== undefined ? (helpText || null) : helpTextOf(field).helpText, displayFormat: next.params.help_text_display_format ?? null };
    if (!confirm) return ok({ dryRun: true, would: preview, note: 'Re-call with confirm:true to apply.' });

    await ctx.client.changeField(applicationId, next as FieldDefinition);
    return ok({ updated: true, ...preview, note: 'Submitted. change_field applies asynchronously; re-read the field in a moment to see it reflected.' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

import { generateFieldSlug } from './formulas.js';

/** Build a field definition envelope (params pass through to SmartSuite, which fills defaults). */
export function buildFieldDef(slug: string, label: string, fieldType: string, params: Record<string, unknown> = {}): FieldDefinition {
  return { slug, label, field_type: fieldType, params: params as FieldDefinition['params'] };
}

const SELECT_FIELD_TYPES = new Set(['singleselectfield', 'multipleselectfield', 'statusfield']);
/** Single/multi select choices carry a description (`value_help_text`) and numeric value (`weight`); status choices do not. */
const WEIGHTED_SELECT_TYPES = new Set(['singleselectfield', 'multipleselectfield']);
/** SmartSuite's default choice-color palette (the sequence new choices cycle through). */
const CHOICE_PALETTE = [
  '#0C41F3', '#00B3FA', '#199A27', '#F1273F', '#FF702E', '#FDA80D', '#673DB6', '#CD286A', '#00B2A8', '#2D2D2D',
  '#3A86FF', '#4ECCFD', '#3EAC40', '#FF5757', '#FF9210', '#FFB938', '#883CD0', '#EC506E', '#17C4C4', '#6A849B',
];

/**
 * For select-type fields, normalize every choice to the shape SmartSuite's UI produces, so MCP-created
 * choices render and behave identically:
 *  - `value_color` / `value_order` (all select types): a choice with no color renders incorrectly until
 *    you open field settings and pick one, so we assign colors from the default palette (by position).
 *  - `value_help_text` (single/multi only): the choice *description* shown in the dropdown; defaults to ''.
 *  - `weight` (single/multi only): the choice's *numeric value* (used by formulas/rollups); defaults to 1,
 *    matching the UI. Callers set it per choice to give options distinct numeric values.
 * Any explicitly-provided value is preserved.
 */
export function normalizeChoices(fieldType: string, params: Record<string, unknown>): Record<string, unknown> {
  if (!SELECT_FIELD_TYPES.has(fieldType) || !Array.isArray(params?.['choices'])) return params;
  const weighted = WEIGHTED_SELECT_TYPES.has(fieldType);
  const choices = (params['choices'] as Array<Record<string, unknown>>).map((c, i) => ({
    ...c,
    value_color: c['value_color'] ?? CHOICE_PALETTE[i % CHOICE_PALETTE.length],
    value_order: c['value_order'] ?? i,
    ...(weighted
      ? { value_help_text: c['value_help_text'] ?? '', weight: c['weight'] ?? 1 }
      : {}),
  }));
  return { ...params, choices };
}

/** Shallow-merge a params patch onto existing params (patch keys win; others preserved). */
export function mergeFieldParams(existing: Record<string, unknown>, patch: Record<string, unknown>): Record<string, unknown> {
  return { ...existing, ...patch };
}

function fieldSummary(f: (FieldDefinition & Record<string, unknown>) | undefined): Record<string, unknown> | null {
  if (!f) return null;
  return { slug: f.slug, label: f.label, fieldType: f.field_type, paramKeys: Object.keys(f.params ?? {}).sort() };
}

/**
 * Create a field of any type. The caller supplies field_type + (optional, sparse) params; SmartSuite
 * fills type defaults. The tool generates the slug, places the field in the record-view layout, and
 * re-reads to report the result (add_field returns an empty body). Schema-write gated; dry-run unless confirm.
 */
export async function handleCreateField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const fieldType = args['fieldType'] as string;
  const label = args['label'] as string;
  const afterFieldSlug = (args['afterFieldSlug'] as string | undefined) ?? '';
  const params = (args['params'] && typeof args['params'] === 'object' && !Array.isArray(args['params'])) ? (args['params'] as Record<string, unknown>) : {};
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!fieldType?.trim()) return err('SMARTSUITE_VALIDATION_ERROR', 'fieldType is required (e.g. textfield, numberfield, singleselectfield, linkedrecordfield).');
  if (!label?.trim()) return err('SMARTSUITE_VALIDATION_ERROR', 'label is required.');

  const slug = generateFieldSlug();
  const field = buildFieldDef(slug, label, fieldType, normalizeChoices(fieldType, params));
  try {
    if (!confirm) {
      return ok({ dryRun: true, would: { slug, fieldType, label, paramKeys: Object.keys(params).sort(), afterFieldSlug: afterFieldSlug || '(end)' }, note: 'SmartSuite fills type defaults for omitted params. Re-call with confirm:true to create.' });
    }
    await ctx.client.addField(applicationId, field, afterFieldSlug);
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const created = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    return ok({ created: true, slug, field: fieldSummary(created) });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/**
 * Update a field: change its label and/or merge a params patch (read-modify-write the full field
 * definition, then PUT via change_field). Applies asynchronously. Schema-write gated; dry-run unless confirm.
 */
export async function handleUpdateField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const label = args['label'] as string | undefined;
  const params = (args['params'] && typeof args['params'] === 'object' && !Array.isArray(args['params'])) ? (args['params'] as Record<string, unknown>) : undefined;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');
  if (label === undefined && params === undefined) {
    return err('SMARTSUITE_VALIDATION_ERROR', 'Provide label and/or params (a patch of param keys to set) to update.');
  }

  try {
    const app = await ctx.client.getApplication(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug) as (FieldDefinition & Record<string, unknown>) | undefined;
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);

    const next = JSON.parse(JSON.stringify(field)) as Record<string, any>;
    if (typeof label === 'string') next['label'] = label;
    if (params) next['params'] = normalizeChoices(next['field_type'], mergeFieldParams(next['params'] ?? {}, params));

    const preview = { slug, label: next['label'], fieldType: next['field_type'], changedParams: params ? Object.keys(params).sort() : [] };
    if (!confirm) return ok({ dryRun: true, would: preview, note: 'Re-call with confirm:true to apply.' });

    await ctx.client.changeField(applicationId, next as unknown as FieldDefinition);
    return ok({ updated: true, ...preview, note: 'Submitted. change_field applies asynchronously; re-read the field in a moment to confirm.' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/**
 * Delete a field by slug. Requires readwrite/admin + SMARTSUITE_ENABLE_SCHEMA_WRITE + SMARTSUITE_ENABLE_DELETE.
 * Dry-run preview unless confirm:true. Destructive — the field and its data are removed.
 */
export async function handleDeleteField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;
  if (!ctx.config.enableDelete) {
    return err('MCP_MODE_BLOCKED', 'Field delete is disabled. Set SMARTSUITE_ENABLE_DELETE=true to enable.');
  }

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required.');

  try {
    const app = await ctx.client.getApplicationSchema(applicationId);
    const field = (app.structure ?? []).find((f) => f.slug === slug);
    if (!field) return err('SMARTSUITE_NOT_FOUND', `Field "${slug}" not found in application ${applicationId}.`);
    if (field.params?.system) return err('SMARTSUITE_VALIDATION_ERROR', `Field "${slug}" (${field.label}) is a system field and cannot be deleted.`);

    const info = { slug, label: field.label, fieldType: field.field_type };
    if (!confirm) return ok({ dryRun: true, wouldDelete: info, note: 'Removes the field and its data. Recoverable via smartsuite_restore_field. Re-call with confirm:true to delete.' });
    await ctx.client.deleteField(applicationId, slug);
    return ok({ deleted: true, ...info, restoreHint: 'Recover with smartsuite_restore_field (applicationId + slug).' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/** List soft-deleted fields across a solution's trash (read-only). The API returns them solution-wide
 * without per-application attribution, so results are not app-filtered. */
export async function handleListDeletedFields(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const solutionId = args['solutionId'] as string;
  if (!solutionId) return err('SMARTSUITE_VALIDATION_ERROR', 'solutionId is required (deleted fields are listed per solution).');
  try {
    const res = await ctx.client.listDeletedFields(solutionId);
    const items = res.map((f) => ({ slug: f['slug'], label: f['label'], fieldType: f['field_type'] }));
    return ok({ items, count: items.length, note: 'Restore with smartsuite_restore_field (you must supply the applicationId the field belonged to).' });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}

/** Restore a soft-deleted field back into its application. Gated schema-write + confirm. */
export async function handleRestoreField(args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
  const blocked = schemaWriteGuard(ctx);
  if (blocked) return blocked;

  const applicationId = args['applicationId'] as string;
  const slug = args['slug'] as string;
  const confirm = args['confirm'] === true;
  if (!applicationId) return err('SMARTSUITE_VALIDATION_ERROR', 'applicationId is required.');
  if (!slug) return err('SMARTSUITE_VALIDATION_ERROR', 'slug is required (the deleted field slug, from smartsuite_list_deleted_fields).');

  try {
    if (!confirm) return ok({ dryRun: true, wouldRestore: { applicationId, slug }, hint: 'Re-call with confirm:true to restore this field.' });
    await ctx.client.restoreField(applicationId, slug);
    const app = await ctx.client.getApplicationSchema(applicationId, { forceRefresh: true });
    const field = (app.structure ?? []).find((f) => f.slug === slug);
    return ok({ restored: true, field: field ? { slug: field.slug, label: field.label, fieldType: field.field_type } : { slug } });
  } catch (e) {
    return { content: [{ type: 'text', text: JSON.stringify({ error: toErrorResponse(e) }, null, 2) }], isError: true };
  }
}
