// AUTO-GENERATED by dashboard widget-template discovery (2026-07-10). Minimal valid params
// per widget type, verified live (each creates 201). Tokens __SOLUTION__ / __APPLICATION__ /
// __PRIMARY_FIELD__ / __SELECT_FIELD__ / __DATE_FIELD__ are substituted with the target app's
// values by fillWidgetTemplate() in dashboards.write.ts.

export const WIDGET_TEMPLATES: Record<string, Record<string, unknown>> = {
  "text-block-widget": {
    "content": {
      "type": "doc",
      "content": [
        {
          "type": "paragraph",
          "content": [
            {
              "type": "text",
              "text": "Text"
            }
          ]
        }
      ]
    }
  },
  "heading-widget": {
    "content": {
      "type": "doc",
      "content": [
        {
          "type": "paragraph",
          "content": [
            {
              "type": "text",
              "text": "Text"
            }
          ]
        }
      ]
    }
  },
  "simple-banner-widget": {
    "content": {
      "type": "doc",
      "content": [
        {
          "type": "paragraph",
          "content": [
            {
              "type": "text",
              "text": "Text"
            }
          ]
        }
      ]
    },
    "background": {},
    "action_buttons": {},
    "spacing": {}
  },
  "hero-widget": {
    "general": {
      "content": {},
      "image": {}
    },
    "style": {
      "layout": "left",
      "spacing": "medium",
      "background": {},
      "background_blur": {},
      "color_overlay": {}
    },
    "spacing": {
      "widget_width": "contained",
      "paddings": {}
    },
    "action_buttons": {
      "size": "medium",
      "alignment": "left",
      "items": [],
      "columns": []
    }
  },
  "faq-widget": {
    "layout": "one_column",
    "items": [],
    "display": "accordion"
  },
  "divider-widget": {
    "color": "#3A86FF"
  },
  "list-view-widget": {
    "view_type": "grid",
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "fields_window": {
      "visible_fields": [
        "__PRIMARY_FIELD__"
      ],
      "fixed_fields_count": 1,
      "columns_width": {},
      "collapsed": []
    },
    "row_size_window": {
      "size": "compact",
      "previous_size": "compact"
    },
    "aggregates": {},
    "group_by_window": {
      "group": []
    },
    "filter_window": {
      "new_filters": {
        "operator": "and",
        "conditions": []
      },
      "filter": {
        "operator": "and",
        "fields": []
      }
    },
    "sort_window": {
      "sort": []
    },
    "spotlight_window": {
      "spotlights": [],
      "by_field_colors": null
    },
    "display_options": {
      "records_limit": {
        "limit": 100,
        "enabled": false
      },
      "allow_inline_edit": false,
      "display_toolbar": false,
      "allow_open_record": false
    }
  },
  "card-view-widget": {
    "view_type": "grid",
    "fields_window": {
      "visible_fields": [
        "__PRIMARY_FIELD__"
      ],
      "fixed_fields_count": 1,
      "columns_width": {},
      "collapsed": []
    },
    "sort_window": {
      "sort": []
    },
    "filter_window": {
      "new_filters": {
        "operator": "and",
        "conditions": []
      },
      "filter": {
        "operator": "and",
        "fields": []
      }
    },
    "group_by_window": {
      "group": []
    },
    "spotlight_window": {
      "spotlights": [],
      "by_field_colors": null
    },
    "card_size_window": {
      "size": "s"
    },
    "display_options": {
      "allow_edit": false,
      "display_toolbar": false,
      "allow_open_record": false
    }
  },
  "kanban-view-widget": {
    "fields_window": {
      "visible_fields": [
        "__PRIMARY_FIELD__"
      ],
      "fixed_fields_count": 1,
      "columns_width": {},
      "collapsed": []
    },
    "sort_window": {
      "sort": []
    },
    "filter_window": {
      "new_filters": {
        "operator": "and",
        "conditions": []
      },
      "filter": {
        "operator": "and",
        "fields": []
      }
    },
    "stack_by_window": {
      "columnFieldSlug": "__SELECT_FIELD__",
      "swimlaneFieldSlug": null,
      "collapsedColumns": [],
      "collapsedSwimlanes": [],
      "columnsValues": []
    },
    "spotlight_window": {
      "spotlights": [],
      "by_field_colors": null
    },
    "card_size_window": {
      "size": "s"
    },
    "display_options": {
      "records_limit": {
        "limit": 100,
        "enabled": false
      },
      "allow_inline_edit": false,
      "display_toolbar": false,
      "allow_open_record": false
    }
  },
  "calendar-view-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "source": {
      "id": "__APPLICATION__",
      "solution": "__SOLUTION__",
      "application": "__APPLICATION__",
      "source_type": "application",
      "selected_record": null
    },
    "calendar_window": {
      "fields": [],
      "showRecordsList": false,
      "viewType": "dayGridMonth",
      "displayWeekends": true,
      "externalReportsInfo": []
    },
    "group_by_window": {
      "group": []
    },
    "filter_window": {
      "new_filters": {
        "operator": "and",
        "conditions": []
      }
    },
    "sort_window": {
      "sort": []
    },
    "spotlight_window": {
      "spotlights": [],
      "by_field_colors": null
    },
    "display_options": {
      "records_limit": {
        "limit": 100
      },
      "allow_edit": false,
      "display_toolbar": false,
      "allow_open_record": false
    }
  },
  "timeline-view-widget": {
    "view_type": "grid",
    "sort_window": {
      "sort": []
    },
    "filter_window": {
      "new_filters": {
        "operator": "and",
        "conditions": []
      },
      "filter": {
        "operator": "and",
        "fields": []
      }
    },
    "group_by_window": {
      "group": []
    },
    "spotlight_window": {
      "spotlights": [],
      "by_field_colors": null
    },
    "display_options": {
      "records_limit": {
        "limit": 100
      },
      "allow_edit": false,
      "display_toolbar": false,
      "allow_open_record": false
    },
    "timeline_window": {
      "viewMode": "day",
      "showRecordsList": false,
      "periods": [],
      "fields": []
    }
  },
  "chart-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "source": {
      "id": "__APPLICATION__",
      "solution": "__SOLUTION__",
      "application": "__APPLICATION__",
      "source_type": "application",
      "selected_record": null
    },
    "chart_type": "bar",
    "values": [],
    "group_by": {},
    "totals": {
      "values": [],
      "collapsed": false
    },
    "benchmarks": {
      "values": [],
      "collapsed": false
    },
    "advanced_options": {
      "collapsed": false,
      "value": {
        "show_dots": false,
        "show_data_labels": false
      }
    }
  },
  "pivot-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "row": {
      "sort": {
        "order": "asc",
        "by": "group"
      },
      "field_slug": "__PRIMARY_FIELD__"
    },
    "column": {
      "sort": {
        "order": "asc",
        "by": "group"
      },
      "field_slug": "__PRIMARY_FIELD__"
    },
    "summarize_by": {
      "function_type": "count",
      "field_slug": "__PRIMARY_FIELD__",
      "aggregation": "count"
    }
  },
  "summary-card-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "field_slug": "__PRIMARY_FIELD__",
    "function_type": "count"
  },
  "progress-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "bar_color": "#3A86FF",
    "field_slug": "__PRIMARY_FIELD__",
    "function_type": "count",
    "goal": 100
  },
  "comparison-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "field_slug": "__PRIMARY_FIELD__",
    "function_type": "count"
  },
  "filter-widget": {
    "solution": "__SOLUTION__",
    "application": "__APPLICATION__",
    "enable_search_bar": true
  },
  "record-details-widget": {
    "fields": []
  },
  "data-schema-widget": {}
};
